In [1]:
import numpy as np
array1 = np.array([1, 2, 3])
print('array1 datatype:', type(array1), array1.shape)

array1 datatype: <class 'numpy.ndarray'> (3,)


In [2]:
array2 = np.array([[1, 2, 3], [5, 878, 11]])
print(array2.shape)

(2, 3)


In [3]:
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array3.shape)

(2, 2, 3)


In [4]:
array4 = np.array([1, 2, 'test'])
array4.dtype

dtype('<U11')

In [5]:
array_int = array1.astype('float64')
print(array_int, array_int.dtype, type(array_int))

[1. 2. 3.] float64 <class 'numpy.ndarray'>


In [6]:
sequence_array = np.arange(2, 10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[2 3 4 5 6 7 8 9]
int32 (8,)


In [7]:
zero_array = np.ones((3, 2), dtype = 'int32')
print(zero_array, zero_array.shape)

[[1 1]
 [1 1]
 [1 1]] (3, 2)


In [8]:
array1 = np.arange(10)
array11 = array1.reshape(2, 5)
array22 = array1.reshape(5, 2)
print(array11, '\n\n', array22)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [9]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 2)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1 = np.arange(8)
array3d = array1.reshape(2, 2, 2)
print('array3d:\n', array3d)
print('\n')
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5)
array6 = array1.reshape(-1, 1)
print('array6:\n', array6)

array3d:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array5:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array6:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [11]:
array1 = np.arange(1, 10)
print('array1:', array1)
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [12]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print(array2d[0, 0])
print(array2d[2][0])   #p[a, b] == [a][b]
print(array2d[0, 1])
print(array2d[1, 0])
print(array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
7
2
4
9


In [13]:
array3 = array1d[:]
print(array3, type(array3))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [14]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])  #***: 슬라이싱을 한 쪽만 하고 나머지는 단일 값 인덱스 적용 가능
print('array2d[:2, 0] \n', array2d[0, :2])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]
array2d[:2, 0] 
 [1 2]


In [15]:
array3 = array2d[[0, 1], 2]
print(array3)

array4 = array2d[[0, 1], 0:2]
print(array4)

array5 = array2d[[0, 1]]
print(array5)

[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [16]:
array1d = np.arange(1, 10)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과값:', array3)

array1d > 5 불린 인덱싱 결과값: [6 7 8 9]


In [19]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]     #*** array4 = array1d[ [5, 6, 7, 8] ] (o), array4 = array1d[5, 6, 7, 8] (x)
print('일반 인덱스로 필터링 결과 :',array4)  #*** [a], [b], [c] 고른다 == [a, b, c]

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [24]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

sort_array1 = np.sort(org_array)  #np.sort()
print(sort_array1)

sort_array2 = org_array.sort()  #ndarray.sort()
print(sort_array2)
print(org_array)


원본 행렬: [3 1 9 5]
[1 3 5 9]
None
[1 3 5 9]


In [25]:
sort_array1_desc = np.sort(org_array)[::-1]  #** 내림차순: [::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [30]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [32]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)[::-1]  #*** argsort()
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [33]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], 
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [34]:
A = np.array([[1, 2],
             [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
